spring.application.name=Consultas

spring.datasource.url=jdbc:postgresql://localhost:5432/consultas_db
spring.datasource.username=postgres
spring.datasource.password=gato
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true